-- Seed the 16 weeks for CS 3330 Spring 2026
-- Replace COURSE_UUID with your actual course id after running schema.sql

insert into public.weeks (course_id, week_number, topic, description, due_date, is_active) values
  ('COURSE_UUID', 1,  'Course Introduction & Overview',
   'Meet your fictional team and project. Set up GitHub and Jira.',
   '2026-01-25', false),
  ('COURSE_UUID', 2,  'SDLC Fundamentals',
   'Identify which SDLC phase your project is entering and justify your choice.',
   '2026-02-02', false),
  ('COURSE_UUID', 3,  'SDLC Models: Comparison & Use Cases',
   'Your team debates which SDLC model fits your project. How do you decide?',
   '2026-02-09', false),
  ('COURSE_UUID', 4,  'Agile Methodology Deep Dive',
   'Draft your first Agile manifesto for your team. What principles matter most?',
   '2026-02-16', false),
  ('COURSE_UUID', 5,  'Scrum Framework',
   'Run sprint planning. Handle your first team conflict around estimates.',
   '2026-02-23', true),
  ('COURSE_UUID', 6,  'XP, Lean, Kanban & Other Methods',
   'A stakeholder asks you to switch from Scrum to Kanban mid-project. Respond.',
   '2026-03-02', false),
  ('COURSE_UUID', 7,  'Requirements Engineering',
   'Elicit requirements from a difficult stakeholder. Produce user stories.',
   '2026-03-09', false),
  ('COURSE_UUID', 8,  'Midterm Review & Requirements Workshop',
   'Your requirements doc has gaps your team just discovered. How do you recover?',
   '2026-03-16', false),
  ('COURSE_UUID', 9,  'Software Design Principles',
   'Apply SOLID principles to a design decision your team is debating.',
   '2026-03-23', false),
  ('COURSE_UUID', 10, 'Architectural Styles & Design Patterns',
   'Choose and justify an architectural pattern for your project.',
   '2026-03-30', false),
  ('COURSE_UUID', 11, 'Code Reviews & Industry Tools',
   'Facilitate a code review session. Handle a team member who pushes back.',
   '2026-04-06', false),
  ('COURSE_UUID', 12, 'Configuration Management',
   'Set up branching strategy and config management for your project.',
   '2026-04-13', false),
  ('COURSE_UUID', 13, 'Dependency Management',
   'A dependency has a critical vulnerability. How do you manage it?',
   '2026-04-20', false),
  ('COURSE_UUID', 14, 'CI/CD & DevOps Integration',
   'Design a CI/CD pipeline for your project. Your team resists automation.',
   '2026-04-27', false),
  ('COURSE_UUID', 15, 'Capstone Project Work',
   'Final sprint. Triage what ships vs what gets cut. Defend your decisions.',
   '2026-05-04', false),
  ('COURSE_UUID', 16, 'Final Presentations & Course Wrap-Up',
   'Reflect on your semester as a team lead. What would you do differently?',
   '2026-05-11', false);
